import React, { useState } from 'react';
import {
  Bot,
  FileCode,
  Copy,
  Check,
  Download,
  Plus,
  Trash2,
  Sparkles,
  RotateCcw,
  CheckCircle2,
} from 'lucide-react';

interface SitemapEntry {
  id: string;
  url: string;
  lastMod: string;
  changeFreq: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  priority: string;
}

export const RobotsSitemapGenerator: React.FC = () => {
  const [activeSubTab, setActiveSubTab] = useState<'robots' | 'sitemap'>('robots');

  // Robots.txt state
  const [userAgent, setUserAgent] = useState<string>('*');
  const [crawlDelay, setCrawlDelay] = useState<string>('');
  const [sitemapUrl, setSitemapUrl] = useState<string>('https://www.example.com/sitemap.xml');
  const [disallows, setDisallows] = useState<string[]>(['/admin/', '/private/', '/tmp/']);
  const [allows, setAllows] = useState<string[]>(['/public/', '/wp-content/uploads/']);
  const [newDisallow, setNewDisallow] = useState<string>('');
  const [newAllow, setNewAllow] = useState<string>('');
  const [copiedRobots, setCopiedRobots] = useState<boolean>(false);

  // Sitemap.xml state
  const [sitemapEntries, setSitemapEntries] = useState<SitemapEntry[]>([
    {
      id: '1',
      url: 'https://www.example.com/',
      lastMod: new Date().toISOString().split('T')[0],
      changeFreq: 'daily',
      priority: '1.0',
    },
    {
      id: '2',
      url: 'https://www.example.com/blog',
      lastMod: new Date().toISOString().split('T')[0],
      changeFreq: 'weekly',
      priority: '0.8',
    },
    {
      id: '3',
      url: 'https://www.example.com/about',
      lastMod: new Date().toISOString().split('T')[0],
      changeFreq: 'monthly',
      priority: '0.5',
    },
  ]);
  const [bulkUrls, setBulkUrls] = useState<string>('');
  const [copiedSitemap, setCopiedSitemap] = useState<boolean>(false);

  // Robots text generator
  const generatedRobotsTxt = React.useMemo(() => {
    const lines: string[] = [];
    lines.push(`# Robots.txt generated by DevSEO Tools`);
    lines.push(`User-agent: ${userAgent || '*'}`);

    if (crawlDelay.trim()) {
      lines.push(`Crawl-delay: ${crawlDelay.trim()}`);
    }

    disallows.forEach((d) => {
      if (d.trim()) lines.push(`Disallow: ${d.trim()}`);
    });

    allows.forEach((a) => {
      if (a.trim()) lines.push(`Allow: ${a.trim()}`);
    });

    if (sitemapUrl.trim()) {
      lines.push('');
      lines.push(`Sitemap: ${sitemapUrl.trim()}`);
    }

    return lines.join('\n');
  }, [userAgent, crawlDelay, sitemapUrl, disallows, allows]);

  // Sitemap XML generator
  const generatedSitemapXml = React.useMemo(() => {
    let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
    xml += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;

    sitemapEntries.forEach((entry) => {
      xml += `  <url>\n`;
      xml += `    <loc>${entry.url}</loc>\n`;
      if (entry.lastMod) xml += `    <lastmod>${entry.lastMod}</lastmod>\n`;
      if (entry.changeFreq) xml += `    <changefreq>${entry.changeFreq}</changefreq>\n`;
      if (entry.priority) xml += `    <priority>${entry.priority}</priority>\n`;
      xml += `  </url>\n`;
    });

    xml += `</urlset>`;
    return xml;
  }, [sitemapEntries]);

  // Preset handlers
  const applyRobotsPreset = (type: 'standard' | 'block-all' | 'wordpress') => {
    if (type === 'standard') {
      setUserAgent('*');
      setDisallows(['/admin/', '/private/', '/cart/']);
      setAllows(['/']);
      setCrawlDelay('');
    } else if (type === 'block-all') {
      setUserAgent('*');
      setDisallows(['/']);
      setAllows([]);
      setCrawlDelay('');
    } else if (type === 'wordpress') {
      setUserAgent('*');
      setDisallows(['/wp-admin/', '/trackback/', '/xmlrpc.php', '/feed/']);
      setAllows(['/wp-admin/admin-ajax.php', '/wp-content/uploads/']);
      setCrawlDelay('');
    }
  };

  const handleAddDisallow = () => {
    if (!newDisallow.trim()) return;
    let path = newDisallow.trim();
    if (!path.startsWith('/')) path = `/${path}`;
    setDisallows([...disallows, path]);
    setNewDisallow('');
  };

  const handleAddAllow = () => {
    if (!newAllow.trim()) return;
    let path = newAllow.trim();
    if (!path.startsWith('/')) path = `/${path}`;
    setAllows([...allows, path]);
    setNewAllow('');
  };

  const handleBulkImport = () => {
    if (!bulkUrls.trim()) return;
    const lines = bulkUrls.split('\n').map((l) => l.trim()).filter(Boolean);
    const today = new Date().toISOString().split('T')[0];
    const newItems: SitemapEntry[] = lines.map((u, i) => ({
      id: `bulk-${Date.now()}-${i}`,
      url: u.startsWith('http') ? u : `https://${u}`,
      lastMod: today,
      changeFreq: 'weekly',
      priority: '0.7',
    }));
    setSitemapEntries((prev) => [...prev, ...newItems]);
    setBulkUrls('');
  };

  const handleCopyRobots = () => {
    navigator.clipboard.writeText(generatedRobotsTxt);
    setCopiedRobots(true);
    setTimeout(() => setCopiedRobots(false), 2000);
  };

  const handleDownloadRobots = () => {
    const blob = new Blob([generatedRobotsTxt], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'robots.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopySitemap = () => {
    navigator.clipboard.writeText(generatedSitemapXml);
    setCopiedSitemap(true);
    setTimeout(() => setCopiedSitemap(false), 2000);
  };

  const handleDownloadSitemap = () => {
    const blob = new Blob([generatedSitemapXml], { type: 'application/xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'sitemap.xml';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200/80 shadow-xs">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xs font-semibold uppercase tracking-wider text-indigo-600 bg-indigo-50 px-2.5 py-1 rounded-full">
                Technical Crawling & Indexation
              </span>
              <span className="text-xs text-slate-500 font-medium">Standard Compliance</span>
            </div>
            <h1 className="text-xl font-bold text-slate-900 mt-1">Robots.txt & XML Sitemap Builder</h1>
            <p className="text-sm text-slate-600 mt-1">
              Configure search engine crawling directives, avoid indexation leaks, and generate clean Google-compliant XML sitemaps.
            </p>
          </div>

          {/* Sub-tab switcher */}
          <div className="flex items-center bg-slate-100 p-1 rounded-xl text-xs font-semibold self-start md:self-auto">
            <button
              onClick={() => setActiveSubTab('robots')}
              className={`flex items-center gap-1.5 px-4 py-2 rounded-lg transition-all ${
                activeSubTab === 'robots'
                  ? 'bg-white text-indigo-600 shadow-xs'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <Bot className="w-3.5 h-3.5" />
              <span>Robots.txt Builder</span>
            </button>
            <button
              onClick={() => setActiveSubTab('sitemap')}
              className={`flex items-center gap-1.5 px-4 py-2 rounded-lg transition-all ${
                activeSubTab === 'sitemap'
                  ? 'bg-white text-indigo-600 shadow-xs'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <FileCode className="w-3.5 h-3.5" />
              <span>XML Sitemap Generator</span>
            </button>
          </div>
        </div>
      </div>

      {/* --- ROBOTS.TXT TAB --- */}
      {activeSubTab === 'robots' && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Controls */}
          <div className="lg:col-span-6 space-y-4">
            <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-4">
              <div className="flex items-center justify-between">
                <h2 className="text-xs font-bold text-slate-700 uppercase tracking-wider">
                  Directive Presets
                </h2>
                <div className="flex items-center gap-1.5">
                  <button
                    onClick={() => applyRobotsPreset('standard')}
                    className="px-2.5 py-1 text-xs font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors"
                  >
                    Standard
                  </button>
                  <button
                    onClick={() => applyRobotsPreset('wordpress')}
                    className="px-2.5 py-1 text-xs font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors"
                  >
                    WordPress
                  </button>
                  <button
                    onClick={() => applyRobotsPreset('block-all')}
                    className="px-2.5 py-1 text-xs font-medium text-rose-700 bg-rose-50 hover:bg-rose-100 rounded-lg transition-colors"
                  >
                    Block All (Dev)
                  </button>
                </div>
              </div>

              {/* User-Agent & Crawl Delay */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-semibold text-slate-700 mb-1">User-Agent</label>
                  <select
                    value={userAgent}
                    onChange={(e) => setUserAgent(e.target.value)}
                    className="w-full px-3 py-2 text-xs rounded-lg border border-slate-300 bg-white text-slate-800 outline-none"
                  >
                    <option value="*">* (All Search Engines)</option>
                    <option value="Googlebot">Googlebot (Google Search)</option>
                    <option value="Bingbot">Bingbot (Microsoft Bing)</option>
                    <option value="Baiduspider">Baiduspider</option>
                    <option value="Yandex">Yandex</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-700 mb-1">Crawl-Delay (Seconds, optional)</label>
                  <input
                    type="number"
                    value={crawlDelay}
                    onChange={(e) => setCrawlDelay(e.target.value)}
                    placeholder="e.g. 5"
                    className="w-full px-3 py-2 text-xs rounded-lg border border-slate-300 outline-none"
                  />
                </div>
              </div>

              {/* Sitemap Directive */}
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">XML Sitemap Location</label>
                <input
                  type="text"
                  value={sitemapUrl}
                  onChange={(e) => setSitemapUrl(e.target.value)}
                  placeholder="https://www.example.com/sitemap.xml"
                  className="w-full px-3 py-2 text-xs rounded-lg border border-slate-300 outline-none"
                />
              </div>

              {/* Disallow Paths */}
              <div className="space-y-2 pt-2 border-t border-slate-100">
                <label className="block text-xs font-semibold text-rose-700">
                  Disallowed Paths ({disallows.length})
                </label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={newDisallow}
                    onChange={(e) => setNewDisallow(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleAddDisallow()}
                    placeholder="/secret/ or /cart/"
                    className="flex-1 px-3 py-1.5 text-xs rounded-lg border border-slate-300 outline-none"
                  />
                  <button
                    onClick={handleAddDisallow}
                    className="px-3 py-1.5 bg-rose-600 hover:bg-rose-700 text-white rounded-lg text-xs font-medium inline-flex items-center gap-1"
                  >
                    <Plus className="w-3.5 h-3.5" />
                    <span>Add</span>
                  </button>
                </div>
                <div className="flex flex-wrap gap-1.5 max-h-32 overflow-y-auto pt-1">
                  {disallows.map((p, idx) => (
                    <span
                      key={idx}
                      className="inline-flex items-center gap-1 text-xs bg-rose-50 border border-rose-200 text-rose-800 px-2 py-1 rounded-md font-mono"
                    >
                      <span>Disallow: {p}</span>
                      <button
                        onClick={() => setDisallows(disallows.filter((_, i) => i !== idx))}
                        className="text-rose-500 hover:text-rose-800"
                      >
                        ×
                      </button>
                    </span>
                  ))}
                </div>
              </div>

              {/* Allow Paths */}
              <div className="space-y-2 pt-2 border-t border-slate-100">
                <label className="block text-xs font-semibold text-emerald-700">
                  Allowed Paths ({allows.length})
                </label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={newAllow}
                    onChange={(e) => setNewAllow(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleAddAllow()}
                    placeholder="/public/ or /wp-content/uploads/"
                    className="flex-1 px-3 py-1.5 text-xs rounded-lg border border-slate-300 outline-none"
                  />
                  <button
                    onClick={handleAddAllow}
                    className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg text-xs font-medium inline-flex items-center gap-1"
                  >
                    <Plus className="w-3.5 h-3.5" />
                    <span>Add</span>
                  </button>
                </div>
                <div className="flex flex-wrap gap-1.5 max-h-32 overflow-y-auto pt-1">
                  {allows.map((p, idx) => (
                    <span
                      key={idx}
                      className="inline-flex items-center gap-1 text-xs bg-emerald-50 border border-emerald-200 text-emerald-800 px-2 py-1 rounded-md font-mono"
                    >
                      <span>Allow: {p}</span>
                      <button
                        onClick={() => setAllows(allows.filter((_, i) => i !== idx))}
                        className="text-emerald-500 hover:text-emerald-800"
                      >
                        ×
                      </button>
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Right: Code Output */}
          <div className="lg:col-span-6 space-y-4">
            <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-slate-700 uppercase tracking-wider">
                  Generated robots.txt
                </span>
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleCopyRobots}
                    className="inline-flex items-center gap-1 px-3 py-1.5 text-xs font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors"
                  >
                    {copiedRobots ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-500" />}
                    <span>{copiedRobots ? 'Copied' : 'Copy'}</span>
                  </button>
                  <button
                    onClick={handleDownloadRobots}
                    className="inline-flex items-center gap-1 px-3 py-1.5 text-xs font-semibold text-indigo-700 bg-indigo-50 hover:bg-indigo-100 rounded-lg transition-colors"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Download robots.txt</span>
                  </button>
                </div>
              </div>

              <pre className="p-4 bg-slate-900 text-emerald-400 font-mono text-xs rounded-xl overflow-x-auto min-h-[300px] leading-relaxed shadow-inner">
                {generatedRobotsTxt}
              </pre>

              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 text-xs text-slate-600 flex items-start gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0 mt-0.5" />
                <p>
                  Place this file in your root domain directory (e.g., <code>https://example.com/robots.txt</code>) so Googlebot and Bingbot can read your crawling guidelines before crawling sub-pages.
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* --- SITEMAP.XML TAB --- */}
      {activeSubTab === 'sitemap' && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left: Entries Editor */}
          <div className="lg:col-span-6 space-y-4">
            <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-4">
              <div className="flex items-center justify-between">
                <h2 className="text-xs font-bold text-slate-700 uppercase tracking-wider">
                  Sitemap URLs ({sitemapEntries.length})
                </h2>
                <button
                  onClick={() =>
                    setSitemapEntries([
                      ...sitemapEntries,
                      {
                        id: String(Date.now()),
                        url: 'https://www.example.com/new-page',
                        lastMod: new Date().toISOString().split('T')[0],
                        changeFreq: 'weekly',
                        priority: '0.8',
                      },
                    ])
                  }
                  className="inline-flex items-center gap-1 text-xs font-semibold text-indigo-600 hover:text-indigo-700"
                >
                  <Plus className="w-3.5 h-3.5" />
                  <span>Add URL</span>
                </button>
              </div>

              {/* Entries list */}
              <div className="space-y-2.5 max-h-[320px] overflow-y-auto pr-1">
                {sitemapEntries.map((entry) => (
                  <div
                    key={entry.id}
                    className="p-3 rounded-xl border border-slate-200 bg-slate-50/50 space-y-2 text-xs"
                  >
                    <div className="flex items-center gap-2">
                      <input
                        type="text"
                        value={entry.url}
                        onChange={(e) =>
                          setSitemapEntries(
                            sitemapEntries.map((item) =>
                              item.id === entry.id ? { ...item, url: e.target.value } : item
                            )
                          )
                        }
                        placeholder="https://www.example.com/page"
                        className="flex-1 px-2.5 py-1 text-xs rounded border border-slate-300 bg-white font-mono"
                      />
                      <button
                        onClick={() =>
                          setSitemapEntries(sitemapEntries.filter((item) => item.id !== entry.id))
                        }
                        className="p-1 text-slate-400 hover:text-rose-600 rounded transition-colors"
                        title="Delete URL"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>

                    <div className="grid grid-cols-3 gap-2">
                      <div>
                        <span className="text-[10px] text-slate-500 block mb-0.5">Lastmod</span>
                        <input
                          type="date"
                          value={entry.lastMod}
                          onChange={(e) =>
                            setSitemapEntries(
                              sitemapEntries.map((item) =>
                                item.id === entry.id ? { ...item, lastMod: e.target.value } : item
                              )
                            )
                          }
                          className="w-full px-1.5 py-0.5 text-xs border rounded bg-white"
                        />
                      </div>
                      <div>
                        <span className="text-[10px] text-slate-500 block mb-0.5">Frequency</span>
                        <select
                          value={entry.changeFreq}
                          onChange={(e: any) =>
                            setSitemapEntries(
                              sitemapEntries.map((item) =>
                                item.id === entry.id ? { ...item, changeFreq: e.target.value } : item
                              )
                            )
                          }
                          className="w-full px-1.5 py-0.5 text-xs border rounded bg-white"
                        >
                          <option value="always">always</option>
                          <option value="hourly">hourly</option>
                          <option value="daily">daily</option>
                          <option value="weekly">weekly</option>
                          <option value="monthly">monthly</option>
                          <option value="yearly">yearly</option>
                          <option value="never">never</option>
                        </select>
                      </div>
                      <div>
                        <span className="text-[10px] text-slate-500 block mb-0.5">Priority</span>
                        <select
                          value={entry.priority}
                          onChange={(e) =>
                            setSitemapEntries(
                              sitemapEntries.map((item) =>
                                item.id === entry.id ? { ...item, priority: e.target.value } : item
                              )
                            )
                          }
                          className="w-full px-1.5 py-0.5 text-xs border rounded bg-white"
                        >
                          <option value="1.0">1.0 (Highest)</option>
                          <option value="0.9">0.9</option>
                          <option value="0.8">0.8</option>
                          <option value="0.7">0.7</option>
                          <option value="0.6">0.6</option>
                          <option value="0.5">0.5 (Default)</option>
                          <option value="0.3">0.3</option>
                          <option value="0.1">0.1</option>
                        </select>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Bulk Add Box */}
              <div className="pt-3 border-t border-slate-100 space-y-2">
                <span className="text-xs font-semibold text-slate-700 block">
                  Quick Bulk Import (Paste URL list, one per line)
                </span>
                <textarea
                  value={bulkUrls}
                  onChange={(e) => setBulkUrls(e.target.value)}
                  placeholder="https://www.example.com/services&#10;https://www.example.com/pricing&#10;https://www.example.com/contact"
                  rows={2}
                  className="w-full p-2 text-xs border border-slate-300 rounded-lg outline-none font-mono resize-none"
                />
                <button
                  onClick={handleBulkImport}
                  disabled={!bulkUrls.trim()}
                  className="w-full py-1.5 bg-slate-800 hover:bg-slate-900 disabled:opacity-50 text-white rounded-lg text-xs font-semibold"
                >
                  Import URLs into Sitemap
                </button>
              </div>
            </div>
          </div>

          {/* Right: Sitemap XML preview */}
          <div className="lg:col-span-6 space-y-4">
            <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-slate-700 uppercase tracking-wider">
                  Generated sitemap.xml
                </span>
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleCopySitemap}
                    className="inline-flex items-center gap-1 px-3 py-1.5 text-xs font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors"
                  >
                    {copiedSitemap ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-500" />}
                    <span>{copiedSitemap ? 'Copied' : 'Copy'}</span>
                  </button>
                  <button
                    onClick={handleDownloadSitemap}
                    className="inline-flex items-center gap-1 px-3 py-1.5 text-xs font-semibold text-indigo-700 bg-indigo-50 hover:bg-indigo-100 rounded-lg transition-colors"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Download sitemap.xml</span>
                  </button>
                </div>
              </div>

              <pre className="p-4 bg-slate-900 text-sky-300 font-mono text-xs rounded-xl overflow-x-auto min-h-[300px] leading-relaxed shadow-inner">
                {generatedSitemapXml}
              </pre>

              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 text-xs text-slate-600 flex items-start gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0 mt-0.5" />
                <p>
                  Submit your generated <code>sitemap.xml</code> URL into <strong>Google Search Console</strong> & <strong>Bing Webmaster Tools</strong> to accelerate page indexing and monitor crawling errors.
                </p>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
